src/MVCBlog.Web/Models/Administration/AddBlogEntryFileViewModel.cs
using System;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using MVCBlog.Localization;

namespace MVCBlog.Web.Models.Administration
{
    public class AddBlogEntryFileViewModel
    {
        [Required(ErrorMessageResourceName = "Validation_Required", ErrorMessageResourceType = typeof(Resources))]
        public Guid? BlogEntryId { get; set; }

        [Required(ErrorMessageResourceName = "Validation_Required", ErrorMessageResourceType = typeof(Resources))]
        public IFormFile File { get; set; }
    }
}

src/MVCBlog.Web/Models/Administration/DownloadViewModel.cs
using MVCBlog.Data;
using MVCBlog.Web.Infrastructure.Paging;

namespace MVCBlog.Web.Models.Administration
{
    public class DownloadViewModel
    {
        public string SearchTerm { get; set; }

        public PagedResult<BlogEntry> BlogEntries { get; set; }
    }
}

src/MVCBlog.Web/Models/Administration/EditBlogEntryViewModel.cs
using System.Collections.Generic;
using MVCBlog.Data;

namespace MVCBlog.Web.Models.Administration
{
    public class EditBlogEntryViewModel
    {
        public BlogEntry BlogEntry { get; set; }

        public List<string> SelectedTagNames { get; set; }

        public List<Tag> AllTags { get; set; }

        public List<User> Authors { get; set; }
    }
}

src/MVCBlog.Web/Models/Administration/ImagesSelectionViewModel.cs
using System.Collections.Generic;
using MVCBlog.Data;

namespace MVCBlog.Web.Models.Administration
{
    public class ImagesSelectionViewModel
    {
        public List<Image> Images { get; set; }
    }
}

src/MVCBlog.Web/Models/Administration/ImagesViewModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Http;
using MVCBlog.Data;
using MVCBlog.Localization;
using MVCBlog.Web.Infrastructure.Paging;

namespace MVCBlog.Web.Models.Administration
{
    public class ImagesViewModel
    {
        public string SearchTerm { get; set; }

        public PagedResult<Image> Images { get; set; }

        [Required(ErrorMessageResourceName = "Validation_Required", ErrorMessageResourceType = typeof(Resources))]
        public IFormFile Image { get; set; }
    }
}

src/MVCBlog.Web/Models/Administration/IndexViewModel.cs
using MVCBlog.Data;
using MVCBlog.Web.Infrastructure.Paging;

namespace MVCBlog.Web.Models.Administration
{
    public class IndexViewModel
    {
        public string SearchTerm { get; set; }

        public PagedResult<BlogEntry> BlogEntries { get; set; }
    }
}

src/MVCBlog.Web/Models/Administration/UsersViewModel.cs
using MVCBlog.Data;
using MVCBlog.Web.Infrastructure.Paging;

namespace MVCBlog.Web.Models.Administration
{
    public class UsersViewModel
    {
        public string SearchTerm { get; set; }

        public PagedResult<User> Users { get; set; }
    }
}

src/MVCBlog.Web/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MVCBlog.Business;
using MVCBlog.Business.Commands;
using MVCBlog.Data;
using MVCBlog.Localization;
using MVCBlog.Web.Infrastructure.Excel;
using MVCBlog.Web.Infrastructure.Mvc;
using MVCBlog.Web.Infrastructure.Paging;
using MVCBlog.Web.Models.Administration;

namespace MVCBlog.Web.Controllers
{
    [Authorize]
    public class AdministrationController : Controller
    {
        private readonly EFUnitOfWork unitOfWork;

        private readonly ICommandHandler<AddOrUpdateBlogEntryCommand> addOrUpdateBlogEntryCommandHandler;

        private readonly ICommandHandler<DeleteBlogEntryCommand> deleteBlogEntryCommandHandler;

        private readonly ICommandHandler<AddOrUpdateBlogEntryFileCommand> addOrUpdateBlogEntryFileCommandHandler;

        private readonly ICommandHandler<DeleteBlogEntryFileCommand> deleteBlogEntryFileCommandHandler;

        private readonly ICommandHandler<AddImageCommand> addImageCommandHandler;

        private readonly ICommandHandler<DeleteImageCommand> deleteImageCommandHandler;

        private readonly UserManager<User> userManager;

        public AdministrationController(
            EFUnitOfWork unitOfWork,
            ICommandHandler<AddOrUpdateBlogEntryCommand> addOrUpdateBlogEntryCommandHandler,
            ICommandHandler<DeleteBlogEntryCommand> deleteBlogEntryCommandHandler,
            ICommandHandler<AddOrUpdateBlogEntryFileCommand> addOrUpdateBlogEntryFileCommandHandler,
            ICommandHandler<DeleteBlogEntryFileCommand> deleteBlogEntryFileCommandHandler,
            ICommandHandler<AddImageCommand> addImageCommandHandler,
            ICommandHandler<DeleteImageCommand> deleteImageCommandHandler,
            UserManager<User> userManager)
        {
            this.unitOfWork = unitOfWork;
            this.addOrUpdateBlogEntryCommandHandler = addOrUpdateBlogEntryCommandHandler;
            this.deleteBlogEntryCommandHandler = deleteBlogEntryCommandHandler;
            this.addOrUpdateBlogEntryFileCommandHandler = addOrUpdateBlogEntryFileCommandHandler;
            this.deleteBlogEntryFileCommandHandler = deleteBlogEntryFileCommandHandler;
            this.addImageCommandHandler = addImageCommandHandler;
            this.deleteImageCommandHandler = deleteImageCommandHandler;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index(IndexViewModel model, Paging<BlogEntry> paging, bool? download)
        {
            if (paging.SortColumn == null)
            {
                paging.SetSortExpression(p => p.PublishDate);
                paging.SortDirection = SortDirection.Descending;
            }

            if (download.GetValueOrDefault())
            {
                paging.Top = int.MaxValue;
                paging.Skip = 0;
            }

            IQueryable<BlogEntry> query = this.unitOfWork.BlogEntries
                .AsNoTracking();

            if (model.SearchTerm != null)
            {
                query = query.Where(u => u.Header.Contains(model.SearchTerm));
            }

            model.BlogEntries = await query
                .GetPagedResultAsync(paging);

            if (download.GetValueOrDefault())
            {
                var document = this.GenerateDocument(model.BlogEntries);
                return this.File(document, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "Posts.xlsx");
            }

            return this.View(model);
        }

        [Route("Blog/{year:int}/{month:int}/{day:int}/{id}/Edit")]
        [Route("[controller]/EditBlogEntry")]
        public async Task<ActionResult> EditBlogEntry(string id)
        {
            BlogEntry entry = null;

            if (id == null)
            {
                entry = new BlogEntry()
                {
                    AuthorId = this.userManager.GetUserId(this.User),
                    PublishDate = DateTimeOffset.UtcNow,
                    Tags = new Collection<BlogEntryTag>()
                };
            }
            else
            {
                entry = await this.GetByPermalink(id);

                if (entry == null)
                {
                    return this.NotFound();
                }
            }

            var model = new EditBlogEntryViewModel()
            {
                BlogEntry = entry
            };

            model.SelectedTagNames = model.BlogEntry.Tags.Select(t => t.Tag.Name).OrderBy(t => t).ToList();

            await this.SetTagsAndAuthors(model);

            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Blog/{year:int}/{month:int}/{day:int}/{id}/Edit")]
        [Route("[controller]/EditBlogEntry")]
        public async Task<ActionResult> EditBlogEntry(string id, EditBlogEntryViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                await this.SetTagsAndAuthors(model);
                return this.View(model);
            }

            try
            {
                await this.addOrUpdateBlogEntryCommandHandler.HandleAsync(new AddOrUpdateBlogEntryCommand()
                {
                    Entity = model.BlogEntry,
                    Tags = model.SelectedTagNames
                });
            }
            catch (BusinessRuleException ex)
            {
                this.SetErrorMessage(ex.Message);
                await this.SetTagsAndAuthors(model);
                return this.View(model);
            }

            this.SetSuccessMessage(Resources.SavedSuccessfully);

            return this.Redirect($"/Blog/{model.BlogEntry.Url}/Edit");
        }

        public async Task<ActionResult> DeleteBlogEntry(Guid? id)
        {
            if (!this.ModelState.IsValid)
            {
                return this.NotFound();
            }

            await this.deleteBlogEntryCommandHandler.HandleAsync(new DeleteBlogEntryCommand()
            {
                Id = id.Value
            });

            this.SetSuccessMessage(Resources.DeletedSuccessfully);

            return this.Redirect(this.Request.Headers["Referer"]);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddBlogEntryFile(AddBlogEntryFileViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.Redirect(this.Request.Headers["Referer"]);
            }

            using (var memoryStream = new MemoryStream())
            {
                await model.File.CopyToAsync(memoryStream);
                byte[] file = memoryStream.ToArray();

                await this.addOrUpdateBlogEntryFileCommandHandler.HandleAsync(new AddOrUpdateBlogEntryFileCommand()
                {
                    BlogEntryId = model.BlogEntryId.Value,
                    Data = file,
                    FileName = model.File.FileName
                });
            }

            this.SetSuccessMessage(Resources.SavedSuccessfully);

            return this.Redirect(this.Request.Headers["Referer"]);
        }

        public async Task<ActionResult> DeleteBlogEntryFile(Guid? id)
        {
            if (!id.HasValue)
            {
                return this.NotFound();
            }

            await this.deleteBlogEntryFileCommandHandler.HandleAsync(new DeleteBlogEntryFileCommand()
            {
                Id = id.Value
            });

            return this.Redirect(this.Request.Headers["Referer"]);
        }

        public async Task<ActionResult> ImagesSelection()
        {
            var model = new ImagesSelectionViewModel();

            model.Images = await this.unitOfWork.Images
                .AsNoTracking()
                .OrderByDescending(i => i.CreatedOn)
                .Take(25)
                .ToListAsync();

            return this.PartialView(model);
        }

        public async Task<IActionResult> Downloads(DownloadViewModel model, Paging<BlogEntry> paging)
        {
            if (paging.SortColumn == null)
            {
                paging.SetSortExpression(p => p.PublishDate);
                paging.SortDirection = SortDirection.Descending;
            }

            IQueryable<BlogEntry> query = this.unitOfWork.BlogEntries
                .AsNoTracking()
                .Include(b => b.BlogEntryFiles);

            if (model.SearchTerm != null)
            {
                query = query.Where(u => u.Header.Contains(model.SearchTerm));
            }

            model.BlogEntries = await query
                .GetPagedResultAsync(paging);

            return this.View(model);
        }

        public async Task<IActionResult> Images(ImagesViewModel model, Paging<Image> paging)
        {
            if (paging.SortColumn == null)
            {
                paging.SetSortExpression(p => p.CreatedOn);
                paging.SortDirection = SortDirection.Descending;
            }

            IQueryable<Image> query = this.unitOfWork.Images
                .AsNoTracking();

            if (model.SearchTerm != null)
            {
                query = query.Where(u => u.Name.Contains(model.SearchTerm));
            }

            model.Images = await query
                .GetPagedResultAsync(paging);

            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Images(ImagesViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction();
            }

            using (var ms = new MemoryStream())
            {
                await model.Image.OpenReadStream().CopyToAsync(ms);

src/MVCBlog.Web/Views/Administration/Downloads.cshtml
@model MVCBlog.Web.Models.Administration.DownloadViewModel
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer["Downloads"];
    ViewData["SelectedMenuItem"] = "Downloads";
}

<form class="form-inline d-print-none" method="get">
    <div class="input-group input-group-sm mb-2 mr-sm-2">
        <div class="input-group-prepend">
            <div class="input-group-text"><i class="fa fa-search"></i></div>
        </div>
        <input asp-for="SearchTerm" class="form-control" placeholder="@Localizer["Search"]" />
    </div>
    <input type="hidden" name="@nameof(Model.BlogEntries.Paging.Top)" value="@Model.BlogEntries.Paging.Top" />
    <button type="submit" class="btn btn-primary btn-sm mb-2 mr-2">@Localizer["Filter"]</button>
</form>
@if (Model.BlogEntries.TotalNumberOfItems > 0)
{
    <div class="table-responsive">
        <table class="table table-bordered table-hover table-striped table-sm">
            <colgroup>
                <col />
                <col style="width: 100px;" />
                <col />
                <col style="width: 100px;" />
            </colgroup>
            <thead>
                <tr>
                    <th paged-result="this.Model.BlogEntries" sort-column="@nameof(BlogEntry.Header)">@Html.DisplayNameFor(m => m.BlogEntries.First().Header)</th>
                    <th paged-result="this.Model.BlogEntries" sort-column="@nameof(BlogEntry.Visits)" class="text-right">@Html.DisplayNameFor(m => m.BlogEntries.First().Visits)</th>
                    <th>@Localizer["File"]</th>
                    <th class="text-right">@Localizer["Downloads"]</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var blogEntry in Model.BlogEntries)
                {
                    <tr>
                        <td><a href="~/Blog/@blogEntry.Url">@blogEntry.Header</a></td>
                        <td class="text-right">@blogEntry.Visits</td>
                        <td>
                            @foreach (var blogEntryFile in blogEntry.BlogEntryFiles.OrderBy(f => f.Name))
                            {
                                <a href="~/Blog/Download/@blogEntryFile.Id">@blogEntryFile.Name</a><br />
                            }
                        </td>
                        <td class="text-right">
                            @foreach (var blogEntryFile in blogEntry.BlogEntryFiles.OrderBy(f => f.Name))
                            {
                                @blogEntryFile.Counter<br />
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <pager paged-result="this.Model.BlogEntries"></pager>
}
else
{
    <p>@Localizer["No blog entries found"]</p>
}

src/MVCBlog.Web/Views/Administration/EditBlogEntry.cshtml
@model MVCBlog.Web.Models.Administration.EditBlogEntryViewModel
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer
@{
    var requestCulture = Context.Features.Get<Microsoft.AspNetCore.Localization.IRequestCultureFeature>();
    string language = requestCulture?.RequestCulture.Culture.TwoLetterISOLanguageName == "de" ? "de" : "en";

    bool existingEntry = Model.BlogEntry.Header != null;

    ViewData["Title"] = Model.BlogEntry.Header ?? Localizer["New blog entry"].Value;
    ViewData["SelectedMenuItem"] = "BlogEntries";
}

@if (existingEntry)
{
    <div class="row d-print-none">
        <div class="col-md-8 col-sm-12">
            <a href="~/Blog/@Model.BlogEntry.Url" title="Edit" class="btn btn-outline-primary"><i class="fa fa-globe"></i> @Localizer["Show blog entry"]</a>
            <br /><br />
        </div>
    </div>
}
<div class="row">
    <div class="col-md-8 col-sm-12">
        <h2>@Localizer["Content"]</h2>
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label asp-for="BlogEntry.Header"></label>
                <input asp-for="BlogEntry.Header" class="form-control" />
                <span asp-validation-for="BlogEntry.Header" class="text-danger"></span>
            </div>
            @if (existingEntry)
            {
                <div class="form-group">
                    <label asp-for="BlogEntry.Permalink"></label>
                    <input asp-for="BlogEntry.Permalink" class="form-control" />
                    <span asp-validation-for="BlogEntry.Permalink" class="text-danger"></span>
                </div>
            }
            <div class="form-group">
                <label asp-for="BlogEntry.ShortContent"></label> (<a href="https://de.wikipedia.org/wiki/Markdown" target="_blank">Markdown</a>)
                <textarea asp-for="BlogEntry.ShortContent" class="form-control" rows="5"></textarea>
                <span asp-validation-for="BlogEntry.ShortContent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogEntry.Content"></label> (<a href="https://de.wikipedia.org/wiki/Markdown" target="_blank">Markdown</a>)
                <partial name="_InsertImage" />
                <textarea asp-for="BlogEntry.Content" class="form-control" rows="10"></textarea>
                <span asp-validation-for="BlogEntry.Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BlogEntry.AuthorId"></label>
                <select asp-for="BlogEntry.AuthorId" asp-items="Model.Authors.Select(a => new SelectListItem() { Value = a.Id, Text = a.ToString() })" class="form-control">
                    <option value="">-</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="BlogEntry.Tags"></label>
                <select asp-for="SelectedTagNames" class="select2" multiple style="width: 100%">
                    @foreach (var tag in Model.AllTags)
                    {
                        if (Model.SelectedTagNames.Any(t => t == tag.Name))
                        {
                            <option value="@tag.Name" selected>@tag.Name</option>
                        }
                        else
                        {
                            <option value="@tag.Name">@tag.Name</option>
                        }
                    }
                </select>
            </div>
            <div class="form-group form-check">
                <input asp-for="BlogEntry.Visible" type="checkbox" class="form-check-input">
                <label asp-for="BlogEntry.Visible" class="form-check-label"></label>
            </div>
            <div class="form-group">
                <label asp-for="BlogEntry.PublishDate"></label>
                <input asp-for="BlogEntry.PublishDate" class="form-control form-control-sm gijgodatetimepicker" type="text" value="@Model.BlogEntry.PublishDate.ToString("dd.MM.yyyy HH:mm")" />
                <span asp-validation-for="BlogEntry.PublishDate" class="text-danger"></span>
            </div>
            <div class="form-group d-print-none">
                <input asp-for="BlogEntry.CreatedOn" type="hidden" />
                <input asp-for="BlogEntry.Id" type="hidden" />
                <button type="submit" class="btn btn-primary">@Localizer["Save"]</button>
            </div>
        </form>
    </div>
    <div class="col-lg-4 col-sm-12">
        @if (existingEntry)
        {
            var blogEntryFileViewModel = new MVCBlog.Web.Models.Administration.AddBlogEntryFileViewModel()
            {
                BlogEntryId = Model.BlogEntry.Id
            };

            <h2>@Localizer["Files"]</h2>
            <partial name="_AddBlogEntryFile" model="@blogEntryFileViewModel" />
            <br />

            if (Model.BlogEntry.BlogEntryFiles.Count > 0)
            {
                <div class="table-responsive">
                    <table class="table table-bordered table-hover table-striped table-sm">
                        <colgroup>
                            <col />
                            <col style="width: 100px;" />
                            <col style="width: 50px;" />
                        </colgroup>
                        <thead>
                            <tr>
                                <th>@Html.DisplayNameFor(m => m.BlogEntry.BlogEntryFiles.First().Name)</th>
                                <th class="text-right">@Html.DisplayNameFor(m => m.BlogEntry.BlogEntryFiles.First().Counter)</th>
                                <th class="d-print-none"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var blogEntryFile in Model.BlogEntry.BlogEntryFiles)
                            {
                                <tr>
                                    <td><a href="~/Blog/Download/@blogEntryFile.Id">@blogEntryFile.Name</a></td>
                                    <td class="text-right">@blogEntryFile.Counter</td>
                                    <td class="text-right d-print-none">
                                        <a asp-controller="Administration" asp-action="DeleteBlogEntryFile" asp-route-id="@blogEntryFile.Id" title="@Localizer["Delete"]" class="confirmdelete" data-confirmmessage="@Localizer["Really delete file?"]"><i class="fa fa-trash text-danger"></i></a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            }
        }
    </div>
</div>

src/MVCBlog.Web/Views/Administration/Images.cshtml
@model MVCBlog.Web.Models.Administration.ImagesViewModel
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer["Images"];
    ViewData["SelectedMenuItem"] = "Images";
}

<form asp-controller="Administration" asp-action="Images" enctype="multipart/form-data" class="form-inline d-print-none">
    <div class="form-group input-group-sm">
        <input asp-for="Image" class="form-control" />
        <button type="submit" class="btn btn-info btn-sm ml-2">@Localizer["Add"]</button>
    </div>
</form>
<br class="d-print-none" />
<br class="d-print-none" />
<form class="form-inline d-print-none" method="get">
    <div class="input-group input-group-sm mb-2 mr-sm-2">
        <div class="input-group-prepend">
            <div class="input-group-text"><i class="fa fa-search"></i></div>
        </div>
        <input asp-for="SearchTerm" class="form-control" placeholder="@Localizer["Search"]" />
    </div>
    <input type="hidden" name="@nameof(Model.Images.Paging.Top)" value="@Model.Images.Paging.Top" />
    <button type="submit" class="btn btn-primary btn-sm mb-2 mr-2">@Localizer["Filter"]</button>
</form>
@if (Model.Images.TotalNumberOfItems > 0)
{
    foreach (var image in Model.Images)
    {
        <figure class="figure mr-3 mb-3">
            <a href="~/blogimages/@image.Path"><img src="~/blogimages/@image.Path" alt="@image.Name" class="img-thumbnail" style="max-width:250px; max-height:250px" /></a>
            <figcaption class="figure-caption mt-1">@image.Name <a asp-controller="Administration" asp-action="DeleteImage" asp-route-id="@image.Id" class="float-right d-print-none confirmdelete" title="@Localizer["Delete"]" data-confirmmessage="@Localizer["Really delete image?"]"><i class="fa fa-trash text-danger"></i></a></figcaption>
        </figure>
    }

    <pager paged-result="this.Model.Images"></pager>
}
else
{
    <p>@Localizer["No images found"]</p>
}

src/MVCBlog.Web/Views/Administration/Index.cshtml
@model MVCBlog.Web.Models.Administration.IndexViewModel
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer
@{
    ViewData["Title"] = Localizer["Blog entries"];
    ViewData["SelectedMenuItem"] = "BlogEntries";
}

<a asp-controller="Administration" asp-action="EditBlogEntry" class="btn btn-primary d-print-none"><i class="fa fa-file" aria-hidden="true"></i> @Localizer["New blog entry"]</a>
<br class="d-print-none" />
<br class="d-print-none" />
<form class="form-inline d-print-none" method="get">
    <div class="input-group input-group-sm mb-2 mr-sm-2">
        <div class="input-group-prepend">
            <div class="input-group-text"><i class="fa fa-search"></i></div>
        </div>
        <input asp-for="SearchTerm" class="form-control" placeholder="@Localizer["Search"]" />
    </div>
    <input type="hidden" name="@nameof(Model.BlogEntries.Paging.Top)" value="@Model.BlogEntries.Paging.Top" />
    <button type="submit" class="btn btn-primary btn-sm mb-2 mr-2">@Localizer["Filter"]</button>
    <button type="submit" name="Download" value="True" class="btn btn-success btn-sm mb-2"><i class="fa fa-file-excel" aria-hidden="true"></i> @Localizer["Download"]</button>
</form>
@if (Model.BlogEntries.TotalNumberOfItems > 0)
{
    <div class="table-responsive">
        <table class="table table-bordered table-hover table-striped table-sm">
            <colgroup>
                <col />
                <col style="width: 170px;" />
                <col style="width: 170px;" />
                <col style="width: 100px;" />
                <col style="width: 70px;" />
            </colgroup>
            <thead>
                <tr>
                    <th paged-result="this.Model.BlogEntries" sort-column="@nameof(BlogEntry.Header)">@Html.DisplayNameFor(m => m.BlogEntries.First().Header)</th>
                    <th paged-result="this.Model.BlogEntries" sort-column="@nameof(BlogEntry.PublishDate)">@Html.DisplayNameFor(m => m.BlogEntries.First().PublishDate)</th>
                    <th paged-result="this.Model.BlogEntries" sort-column="@nameof(BlogEntry.UpdateDate)">@Html.DisplayNameFor(m => m.BlogEntries.First().UpdateDate)</th>
                    <th paged-result="this.Model.BlogEntries" sort-column="@nameof(BlogEntry.Visits)" class="text-right">@Html.DisplayNameFor(m => m.BlogEntries.First().Visits)</th>
                    <th class="d-print-none"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var blogEntry in Model.BlogEntries)
                {
                    <tr>
                        <td><a href="~/Blog/@blogEntry.Url/Edit">@blogEntry.Header</a></td>
                        <td class="text-right">@blogEntry.PublishDate.DateTime.ToShortDateString() @blogEntry.PublishDate.DateTime.ToShortTimeString()</td>
                        <td class="text-right">@blogEntry.UpdateDate.DateTime.ToShortDateString() @blogEntry.UpdateDate.DateTime.ToShortTimeString()</td>
                        <td class="text-right">@blogEntry.Visits</td>
                        <td class="text-right d-print-none">
                            <a href="~/Blog/@blogEntry.Url" title="Edit"><i class="fa fa-globe"></i></a>
                            <a href="~/Blog/@blogEntry.Url/Edit" title="Edit"><i class="fa fa-edit"></i></a>
                            <a asp-controller="Administration" asp-action="DeleteBlogEntry" asp-route-id="@blogEntry.Id" title="@Localizer["Delete"]" class="confirmdelete" data-confirmmessage="@Localizer["Really delete blog entry?"]"><i class="fa fa-trash text-danger"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <pager paged-result="this.Model.BlogEntries"></pager>
}
else
{
    <p>@Localizer["No blog entries found"]</p>
}

src/MVCBlog.Web/Views/Administration/_AddBlogEntryFile.cshtml
@model MVCBlog.Web.Models.Administration.AddBlogEntryFileViewModel
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer

<form asp-controller="Administration" asp-action="AddBlogEntryFile" enctype="multipart/form-data" class="form-inline d-print-none">
    <div class="form-group input-group-sm">
        <input asp-for="File" class="form-control" />
        <span asp-validation-for="File" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input asp-for="BlogEntryId" type="hidden" />
        <button type="submit" class="btn btn-info btn-sm ml-2">@Localizer["Add"]</button>
    </div>
</form>