src/MVCBlog.Web/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using Markdig;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Options;
using Microsoft.SyndicationFeed;
using Microsoft.SyndicationFeed.Rss;
using MVCBlog.Business;
using MVCBlog.Business.Commands;
using MVCBlog.Business.IO;
using MVCBlog.Data;
using MVCBlog.Web.Infrastructure.Mvc;
using MVCBlog.Web.Infrastructure.Paging;
using MVCBlog.Web.Models.Blog;

namespace MVCBlog.Web.Controllers
{
    public class BlogController : Controller
    {
        private const int EntriesPerPage = 10;

        private readonly EFUnitOfWork unitOfWork;

        private readonly IBlogEntryFileFileProvider fileProvider;

        private readonly ICommandHandler<AddBlogEntryCommentCommand> addBlogEntryCommentCommandHandler;

        private readonly ICommandHandler<DeleteBlogEntryCommentCommand> deleteBlogEntryCommentCommandHander;

        private readonly ICommandHandler<DeleteBlogEntryCommand> deleteBlogEntryCommandHander;

        private readonly ICommandHandler<IncrementBlogEntryVisitsCommand> incrementBlogEntryVisitsCommand;

        private readonly ICommandHandler<IncrementBlogEntryFileCounterCommand> incrementBlogEntryFileCounterCommandHandler;

        private readonly BlogSettings blogSettings;

        public BlogController(
            EFUnitOfWork unitOfWork,
            IBlogEntryFileFileProvider fileProvider,
            ICommandHandler<AddBlogEntryCommentCommand> addBlogEntryCommentCommandHandler,
            ICommandHandler<DeleteBlogEntryCommentCommand> deleteBlogEntryCommentCommandHander,
            ICommandHandler<DeleteBlogEntryCommand> deleteBlogEntryCommandHander,
            ICommandHandler<IncrementBlogEntryVisitsCommand> incrementBlogEntryVisitsCommand,
            ICommandHandler<IncrementBlogEntryFileCounterCommand> incrementBlogEntryFileCounterCommandHandler,
            IOptions<BlogSettings> optionsAccessor)
        {
            this.unitOfWork = unitOfWork;
            this.fileProvider = fileProvider;

            this.addBlogEntryCommentCommandHandler = addBlogEntryCommentCommandHandler;
            this.deleteBlogEntryCommentCommandHander = deleteBlogEntryCommentCommandHander;
            this.deleteBlogEntryCommandHander = deleteBlogEntryCommandHander;
            this.incrementBlogEntryVisitsCommand = incrementBlogEntryVisitsCommand;
            this.incrementBlogEntryFileCounterCommandHandler = incrementBlogEntryFileCounterCommandHandler;

            this.blogSettings = optionsAccessor.Value;
        }

        [Route("")]
        [Route("[controller]")]
        [Route("[controller]/Index")]
        [Route("[controller]/Tag/{tag}")]
        public async Task<ActionResult> Index(Paging<BlogEntry> paging, string tag, string search)
        {
            paging.SetSortExpression(p => p.PublishDate);
            paging.SortDirection = SortDirection.Descending;
            paging.Top = EntriesPerPage;

            var query = this.unitOfWork.BlogEntries
                            .Include(b => b.Author)
                            .Include(b => b.BlogEntryComments)
                            .Include(b => b.Tags)
                            .ThenInclude(b => b.Tag)
                            .AsNoTracking()
                            .Where(e => (e.Visible && e.PublishDate <= DateTimeOffset.Now) || this.User.Identity.IsAuthenticated);

            if (!string.IsNullOrEmpty(tag))
            {
                query = query.Where(e => e.Tags.Any(t => t.Tag.Name.Equals(tag, StringComparison.OrdinalIgnoreCase)));
            }

            if (!string.IsNullOrEmpty(search))
            {
                foreach (var item in search.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries))
                {
                    query = query.Where(e => e.Header.Contains(item));
                }
            }

            var model = new IndexViewModel()
            {
                Entries = await query.GetPagedResultAsync(paging),
                Tags = await this.unitOfWork.Tags
                    .AsNoTracking()
                    .OrderBy(t => t.Name)
                    .ToListAsync(),
                PopularBlogEntries = await this.unitOfWork.BlogEntries
                    .AsNoTracking()
                    .Where(e => (e.Visible && e.PublishDate <= DateTimeOffset.Now) || this.User.Identity.IsAuthenticated)
                    .OrderByDescending(b => b.Visits)
                    .Take(5)
                    .ToListAsync(),
                Tag = tag,
                Search = search
            };

            return this.View(model);
        }

        /// <summary>
        /// Shows a single <see cref="BlogEntry"/>.
        /// </summary>
        /// <param name="id">The id.</param>
        /// <returns>A view showing a single <see cref="BlogEntry"/>.</returns>
        [Route("[controller]/{year:int}/{month:int}/{day:int}/{id}")]
        public async Task<ActionResult> Entry(string id)
        {
            var entry = await this.GetByPermalink(id);

            if (entry == null)
            {
                return this.NotFound();
            }

            if (!this.User.Identity.IsAuthenticated)
            {
                await this.incrementBlogEntryVisitsCommand.HandleAsync(new IncrementBlogEntryVisitsCommand()
                {
                    Id = entry.Id
                });

                entry.Visits++;
            }

            return this.View(new EntryViewModel()
            {
                BlogEntry = entry,
                RelatedBlogEntries = await this.GetRelatedBlogEntries(entry)
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [SpamProtection]
        [Route("[controller]/{year:int}/{month:int}/{day:int}/{id}")]
        public async Task<ActionResult> Entry(string id, EntryViewModel model)
        {
            var entry = await this.GetByPermalink(id);

            if (entry == null)
            {
                return this.NotFound();
            }

            if (!this.ModelState.IsValid)
            {
                model.BlogEntry = entry;
                model.RelatedBlogEntries = await this.GetRelatedBlogEntries(entry);

                return this.View(model);
            }

            var blogEntryComment = new BlogEntryComment()
            {
                Name = model.Comment.Name,
                Email = model.Comment.Email,
                Homepage = model.Comment.Homepage,
                Comment = model.Comment.Comment,
                AdminPost = this.User.Identity.IsAuthenticated,
                BlogEntryId = entry.Id
            };

            await this.addBlogEntryCommentCommandHandler.HandleAsync(new AddBlogEntryCommentCommand()
            {
                Entity = blogEntryComment,
                Referer = this.Request.GetTypedHeaders().Referer?.ToString()
            });

            return this.RedirectToAction(nameof(this.Entry), new { Id = id });
        }

        /// <summary>
        /// Returns an RSS-Feed of all <see cref="BlogEntry">BlogEntries</see>.
        /// </summary>
        /// <returns>RSS-Feed of all <see cref="BlogEntry">BlogEntries</see>.</returns>
        [ResponseCache(Duration = 3600)]
        public async Task<ActionResult> Feed()
        {
            var entries = await this.unitOfWork.BlogEntries
                .Include(b => b.Author)
                .Include(b => b.Tags)
                .ThenInclude(t => t.Tag)
                .AsNoTracking()
                .Where(b => b.Visible && b.PublishDate <= DateTimeOffset.UtcNow)
                .OrderByDescending(b => b.PublishDate)
                .ToListAsync();

            string baseUrl = $"{this.Request.Scheme}://{this.Request.Host}{this.Request.PathBase}";

            using (var sw = new StringWriterWithEncoding(Encoding.UTF8))
            {
                using (XmlWriter xmlWriter = XmlWriter.Create(sw, new XmlWriterSettings() { Async = true, Indent = true }))
                {
                    var writer = new RssFeedWriter(xmlWriter);
                    await writer.WriteTitle(this.blogSettings.BlogName);
                    await writer.WriteDescription(this.blogSettings.BlogDescription);
                    await writer.Write(new SyndicationLink(new Uri(baseUrl)));
                    await writer.WriteRaw($"<atom:link href=\"{baseUrl}/Blog/{nameof(this.Feed)}\" rel=\"self\" type=\"application/rss+xml\" xmlns:atom=\"http://www.w3.org/2005/Atom\" />");
                    await writer.Write(new SyndicationImage(new Uri($"{baseUrl}/apple-touch-icon_192.png"))
                    {
                        Title = this.blogSettings.BlogName,
                        Description = this.blogSettings.BlogDescription,
                        Link = new SyndicationLink(new Uri(baseUrl))
                    });

                    if (entries.Count > 0)
                    {
                        await writer.WritePubDate(entries[0].PublishDate);
                    }

                    var pipeline = new MarkdownPipelineBuilder()
                        .UseAdvancedExtensions()
                        .Build();

                    foreach (var blogEntry in entries)
                    {
                        var syndicationItem = new SyndicationItem()
                        {
                            Id = blogEntry.Id.ToString(),
                            Title = blogEntry.Header,
                            Published = blogEntry.PublishDate,
                            LastUpdated = blogEntry.PublishDate > blogEntry.UpdateDate ? blogEntry.PublishDate : blogEntry.UpdateDate,

src/MVCBlog.Web/Controllers/PrivacyController.cs
using Microsoft.AspNetCore.Mvc;

namespace MVCBlog.Web.Controllers
{
    public class PrivacyController : Controller
    {
        public IActionResult Index()
        {
            return this.View();
        }
    }
}

src/MVCBlog.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject Microsoft.AspNetCore.Mvc.Localization.IViewLocalizer Localizer
@inject SignInManager<MVCBlog.Data.User> SignInManager
@inject Microsoft.Extensions.Options.IOptionsMonitor<MVCBlog.Business.BlogSettings> BlogSettings
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @BlogSettings.CurrentValue.BlogName</title>
    <link rel="stylesheet" href="~/dist/combined.min.css" asp-append-version="true" />
    <link rel="shortcut icon" href="~/favicon.ico" type="image/x-icon" />
    <link rel="apple-touch-icon" href="~/apple-touch-icon.png" />
    <link rel="icon" type="image/png" href="~/apple-touch-icon_192.png" sizes="192x192" />
    <meta name="theme-color" content="#2F5890">
    <meta name="msapplication-navbutton-color" content="#2F5890">
    <meta name="apple-mobile-web-app-status-bar-style" content="#2F5890">
    <link rel="alternate" type="application/rss+xml" title="@BlogSettings.CurrentValue.BlogDescription" href="@this.Context.Request.Scheme://@this.Context.Request.Host@this.Context.Request.PathBase}/Blog/Feed" />
</head>
<body>
    <div class="container">
        <header>
            <a href="~/" class="banner d-print-none"></a>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom shadow-sm mb-3">
                <a class="navbar-brand" href="~/">Blog</a>
                @if (SignInManager.IsSignedIn(User))
                {
                    <a asp-area="" asp-controller="Administration" asp-action="Index" class="nav-link text-dark"><i class="fas fa-tools"></i></a>
                }
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Blog" asp-action="Feed"><i class="fas fa-rss"></i></a>
                        </li>
                    </ul>
                    <form class="form-inline" action="~/" method="get">
                        <input class="form-control mr-sm-2" type="search" name="search" placeholder="@Localizer["Search"]" aria-label="Search">
                        <button class="btn btn-outline-dark my-2 my-sm-0" type="submit">@Localizer["Search"]</button>
                    </form>
                </div>
            </nav>
        </header>
        <partial name="_CookieConsentPartial" />

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted text-center d-print-none">
        <div class="container">
            <a asp-area="" asp-controller="Privacy" asp-action="Index"><i class="fas fa-user-shield"></i></a>
            <a asp-area="" asp-controller="Privacy" asp-action="Index">@Localizer["Privacy"]</a>
            @if (!SignInManager.IsSignedIn(User))
            {
                if (BlogSettings.CurrentValue.NewUsersCanRegister)
                {
                    <text>|</text>
                    <a asp-area="Identity" asp-page="/Account/Register"><i class="fas fa-user-plus"></i></a>
                    <a asp-area="Identity" asp-page="/Account/Register">@Localizer["Register"]</a>
                }
                <text>|</text>
                <a asp-area="Identity" asp-page="/Account/Login"><i class="fas fa-sign-in-alt"></i></a>
                <a asp-area="Identity" asp-page="/Account/Login">@Localizer["Login"]</a>
            }
            else
            {
                <text>|</text>
                <a asp-area="Identity" asp-page="/Account/Manage/Index"><i class="fas fa-user-cog"></i></a>
                <a asp-area="Identity" asp-page="/Account/Manage/Index">@Localizer["Settings"]</a>
                <text>|</text>
                <form style="display: inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="/">
                    <button type="submit" class="btn btn-link" style="padding-left: 0;"><i class="fas fa-sign-out-alt"></i> @Localizer["Logout"]</button>
                </form>
            }
        </div>
    </footer>

    <script src="~/dist/combined.min.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>